cc_binary(
    name = "bitwise_operations",
    srcs = [
       "main.cpp"
    ],
    deps = [
        "//tensorflow/cc:cc_ops",
        "//tensorflow/cc:client_session",
        "//tensorflow/core:tensorflow",
        "//tensorflow/cc/DimanNe/tensorflow_utils:tensorflow_utils"
    ],
)
