cc_binary(
    name = "bitwise_operations",
    srcs = [
       "main.cpp"
    ],
    deps = [
        "//tensorflow/cc:grad_ops",
        "//tensorflow/cc:cc_ops",
        "//tensorflow/cc:gradients",

        "//tensorflow/cc:client_session",

        "//tensorflow/cc/DimanNe/tensorflow_utils:tensorflow_utils",
    ],
)
