cc_binary(
    name = "bitwise_operations",
    srcs = [
       "main.cpp"
    ],
    deps = [
        "//tensorflow/cc:grad_ops",
        "//tensorflow/cc:cc_ops",
        "//tensorflow/cc:gradients",

        "//tensorflow/cc:client_session",
        "//tensorflow/core:ops",
        "//tensorflow/core:core_cpu",
        "//tensorflow/core:direct_session",

        "//tensorflow/core:tensorflow",
        # "//tensorflow/core:all_kernels",
        # "//tensorflow/core/kernels:random_ops",
        # "//tensorflow/core/kernels:nn",
        # "//tensorflow/core/kernels:math",
        # "//tensorflow/core/kernels:data_flow",
        # "//tensorflow/core/kernels:control_flow_ops",
        # "//tensorflow/core/kernels:array",

        "//tensorflow/cc/DimanNe/tensorflow_utils:tensorflow_utils",
    ],
)
